
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RBRACK = 11;
  public static final int NE = 30;
  public static final int LT = 29;
  public static final int ELSE = 20;
  public static final int ASGN = 16;
  public static final int IDENT = 5;
  public static final int PLUS = 21;
  public static final int RPAREN = 7;
  public static final int WHILE = 22;
  public static final int LCURL = 8;
  public static final int SLASH = 25;
  public static final int STAR = 24;
  public static final int LBRACK = 10;
  public static final int REF = 17;
  public static final int IF = 3;
  public static final int GT = 28;
  public static final int LPAREN = 6;
  public static final int COLON = 13;
  public static final int LE = 31;
  public static final int OF = 18;
  public static final int INTLIT = 26;
  public static final int TYPE = 14;
  public static final int SEMIC = 15;
  public static final int COMMA = 19;
  public static final int EOF = 0;
  public static final int GE = 27;
  public static final int MINUS = 23;
  public static final int error = 1;
  public static final int PROC = 4;
  public static final int EQ = 32;
  public static final int RCURL = 9;
  public static final int ARRAY = 2;
  public static final int VAR = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ARRAY",
  "IF",
  "PROC",
  "IDENT",
  "LPAREN",
  "RPAREN",
  "LCURL",
  "RCURL",
  "LBRACK",
  "RBRACK",
  "VAR",
  "COLON",
  "TYPE",
  "SEMIC",
  "ASGN",
  "REF",
  "OF",
  "COMMA",
  "ELSE",
  "PLUS",
  "WHILE",
  "MINUS",
  "STAR",
  "SLASH",
  "INTLIT",
  "GE",
  "GT",
  "LT",
  "NE",
  "LE",
  "EQ"
  };
}

